import type { Card, Edge } from "./types";
import { CARD_TYPE_LABELS } from "./constants";
import type { AgentHintExportMode, ExportGoalOverride } from "../store/canvas-store";

/**
 * Generate context.md following Claude's optimal reading pattern:
 * 1. Rules first (highest value per word — top of context gets most attention)
 * 2. Structure second (orientation)
 * 3. Workflows third (sequences)
 * 4. Data/References last (supplementary)
 *
 * Brainstorm cards are always excluded.
 * Reference edges are resolved at their specified scope.
 */
export function generateContextMd(
  projectName: string,
  cards: Card[],
  edges: Edge[],
  goal?: string,
  options?: {
    agentHintExportMode?: AgentHintExportMode;
    includeAgentHints?: boolean;
    includeBrainstorm?: boolean;
    includeCardDocs?: boolean;
    excludedTags?: string[];
    goalOverride?: ExportGoalOverride;
  },
): string {
  const hintMode = options?.includeAgentHints === false
    ? "hidden"
    : (options?.agentHintExportMode ?? "inline");
  const includeBrainstorm = options?.includeBrainstorm ?? false;
  const includeCardDocs = options?.includeCardDocs ?? true;
  const excludedTags = new Set(options?.excludedTags ?? []);

  const activeCards = cards.filter((c) => {
    if (c.type === "brainstorm" && !includeBrainstorm) return false;
    const cardTags = Array.isArray(c.tags) ? c.tags.filter((t): t is string => typeof t === "string") : [];
    if (cardTags.some((t) => excludedTags.has(t))) return false;
    return true;
  });
  const hierarchyEdges = edges.filter((e) => e.edgeType === "hierarchy");
  const flowEdges = edges.filter((e) => e.edgeType === "flow");
  const refEdges = edges.filter((e) => e.edgeType === "reference");
  const goalProfile = resolveGoalProfile(goal, options?.goalOverride);
  const collectedHints: { cardTitle: string; hint: string }[] = [];

  const lines: string[] = [];

  lines.push(`# ${projectName}`);
  lines.push("");
  lines.push(`> Generated by flo from ${activeCards.length} cards and ${edges.length} connections.`);
  if (goal) {
    lines.push(`> Goal: ${goal}`);
    lines.push(`> Agent focus: ${goalProfile.prompt}`);
  }
  lines.push("");

  // --- Section 1: Rules ---
  const ruleCards = activeCards.filter(
    (c) => (c.type === "project" || c.type === "process") && c.body.trim()
  );
  if (ruleCards.length > 0) {
    lines.push("## Rules");
    lines.push("");
    for (const card of sortCardsForGoal(ruleCards, goalProfile)) {
      const bodyLines = card.body.split("\n").filter((l) => l.trim());
      for (const line of bodyLines) {
        lines.push(`- ${line.trim()}`);
      }
    }
    lines.push("");
  }

  // --- Section 2: Structure ---
  const roots = activeCards.filter(
    (c) => !hierarchyEdges.some((e) => e.target === c.id)
  );
  const childrenOf = (parentId: string): Card[] =>
    sortCardsForGoal(
      hierarchyEdges
      .filter((e) => e.source === parentId)
      .map((e) => activeCards.find((c) => c.id === e.target))
      .filter(Boolean) as Card[],
      goalProfile
    );

  if (hierarchyEdges.length > 0) {
    lines.push("## Structure");
    lines.push("");
    function renderTree(card: Card, indent: number) {
      const prefix = "  ".repeat(indent) + "- ";
      const tag = `[${CARD_TYPE_LABELS[card.type]}]`;
      const tags = Array.isArray(card.tags)
        ? card.tags.filter((value): value is string => typeof value === "string")
        : [];
      const metadataIndent = "  ".repeat(indent) + "  ";
      lines.push(`<!-- flo-card:${card.id} -->`);
      lines.push(`${prefix}${tag} ${card.title}`);
      if (card.body.trim()) {
        lines.push(`${metadataIndent}Summary: ${card.body.split("\n")[0].trim()}`);
      }
      if (tags.length) {
        lines.push(`${metadataIndent}Tags: ${tags.map((value) => `#${value}`).join(" ")}`);
      }
      if (card.agentHint?.trim() && hintMode !== "hidden") {
        if (hintMode === "inline") {
          lines.push(`${metadataIndent}Agent: ${card.agentHint.trim()}`);
        } else {
          collectedHints.push({ cardTitle: card.title, hint: card.agentHint.trim() });
        }
      }
      for (const child of childrenOf(card.id)) {
        renderTree(child, indent + 1);
      }
    }
    for (const root of sortCardsForGoal(roots, goalProfile)) {
      renderTree(root, 0);
    }
    lines.push("");
  }

  // --- Section 3: Workflows ---
  if (flowEdges.length > 0) {
    lines.push("## Workflows");
    lines.push("");

    const flowTargets = new Set(flowEdges.map((e) => e.target));
    const flowStarts = flowEdges
      .filter((e) => !flowTargets.has(e.source))
      .map((e) => e.source);
    const uniqueStarts = [...new Set(flowStarts)];

    for (const startId of sortCardIdsForGoal(uniqueStarts, activeCards, goalProfile)) {
      let current: string | undefined = startId;
      let step = 1;
      const visited = new Set<string>();
      while (current && !visited.has(current)) {
        visited.add(current);
        const card = activeCards.find((c) => c.id === current);
        if (card) {
          const hintSuffix =
            card.agentHint?.trim() && hintMode === "inline"
              ? ` _(Agent: ${card.agentHint.trim()})_`
              : "";
          if (card.agentHint?.trim() && hintMode === "section") {
            collectedHints.push({ cardTitle: card.title, hint: card.agentHint.trim() });
          }
          lines.push(
            `${step}. **${card.title}**${card.body ? " — " + card.body.split("\n")[0] : ""}${hintSuffix}`
          );
          step++;
        }
        const next = flowEdges.find((e) => e.source === current);
        current = next?.target;
      }
      lines.push("");
    }
  }

  // --- Section 4: Context References ---
  if (refEdges.length > 0) {
    lines.push("## Context References");
    lines.push("");

    for (const ref of sortEdgesForGoal(refEdges, activeCards, goalProfile)) {
      const source = activeCards.find((c) => c.id === ref.source);
      const target = activeCards.find((c) => c.id === ref.target);
      if (!source || !target) continue;

      switch (ref.referenceScope) {
        case "title":
          lines.push(`- When working on ${source.title}, see also: ${target.title}`);
          break;
        case "summary":
          lines.push(`- When working on ${source.title}, see: **${target.title}** — ${target.body || "(no description)"}`);
          break;
        case "section":
          lines.push(`- When working on ${source.title}, see: **${target.title}** > ${ref.referenceSectionHint || "relevant section"}`);
          break;
        case "full":
        default:
          lines.push(`- When working on ${source.title}, see: **${target.title}** (full context)`);
          if (target.body) lines.push(`  ${target.body}`);
          break;
      }
    }
    lines.push("");
  }

  // --- Section 5: Agent Hints (collected, if mode=section) ---
  if (hintMode === "section" && collectedHints.length > 0) {
    lines.push("## Agent Hints");
    lines.push("");
    for (const { cardTitle, hint } of collectedHints) {
      lines.push(`- **${cardTitle}**: ${hint}`);
    }
    lines.push("");
  }

  // --- Section 6: Card Documents ---
  if (includeCardDocs) {
    const fullDocCards = activeCards.filter(
      (c) => c.hasDoc && c.docContent.trim()
    );
    const fullRefTargets = new Set(
      refEdges.filter((e) => e.referenceScope === "full").map((e) => e.target)
    );
    const docsToInclude = fullDocCards.filter(
      (c) =>
        !hierarchyEdges.some((e) => e.target === c.id) ||
        fullRefTargets.has(c.id)
    );

    if (docsToInclude.length > 0) {
      lines.push("## Detailed Documents");
      lines.push("");
      for (const card of sortCardsForGoal(docsToInclude, goalProfile)) {
        lines.push(`### ${card.title}`);
        lines.push(`<!-- flo-card:${card.id} -->`);
        lines.push("");
        const plainText = docHtmlToPlainMarkdown(card.docContent);
        lines.push(plainText);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

function resolveGoalProfile(
  goal?: string,
  goalOverride: ExportGoalOverride = "auto"
): {
  prompt: string;
  priority: Record<Card["type"], number>;
} {
  const normalized = goal?.toLowerCase() ?? "";

  if (goalOverride === "implementation") {
    return {
      prompt: "Prioritize execution order, implementation details, and blockers over broad theory.",
      priority: { process: 4, project: 3, reference: 2, brainstorm: 1 },
    };
  }

  if (goalOverride === "review") {
    return {
      prompt: "Prioritize constraints, architecture, and evidence before proposed changes.",
      priority: { project: 4, reference: 3, process: 2, brainstorm: 1 },
    };
  }

  if (goalOverride === "brainstorm") {
    return {
      prompt: "Surface possibilities first, then supporting references and implementation details.",
      priority: { brainstorm: 4, project: 3, process: 2, reference: 1 },
    };
  }

  if (/(implement|build|ship|code|fix|deliver)/.test(normalized)) {
    return {
      prompt: "Prioritize execution order, implementation details, and blockers over broad theory.",
      priority: { process: 4, project: 3, reference: 2, brainstorm: 1 },
    };
  }

  if (/(review|audit|architecture|analy[sz]e|risk)/.test(normalized)) {
    return {
      prompt: "Prioritize constraints, architecture, and evidence before proposed changes.",
      priority: { project: 4, reference: 3, process: 2, brainstorm: 1 },
    };
  }

  if (/(brainstorm|idea|feature|explore|concept)/.test(normalized)) {
    return {
      prompt: "Surface possibilities first, then supporting references and implementation details.",
      priority: { brainstorm: 4, project: 3, process: 2, reference: 1 },
    };
  }

  return {
    prompt: "Prioritize the most actionable and structurally important cards first.",
    priority: { project: 4, process: 3, reference: 2, brainstorm: 1 },
  };
}

function sortCardsForGoal(cards: Card[], goalProfile: ReturnType<typeof resolveGoalProfile>): Card[] {
  return [...cards].sort((a, b) => {
    const priorityDiff = goalProfile.priority[b.type] - goalProfile.priority[a.type];
    if (priorityDiff !== 0) {
      return priorityDiff;
    }

    return a.title.localeCompare(b.title);
  });
}

function sortCardIdsForGoal(
  ids: string[],
  cards: Card[],
  goalProfile: ReturnType<typeof resolveGoalProfile>
): string[] {
  return [...ids].sort((a, b) => {
    const cardA = cards.find((card) => card.id === a);
    const cardB = cards.find((card) => card.id === b);
    if (!cardA || !cardB) {
      return 0;
    }

    const priorityDiff = goalProfile.priority[cardB.type] - goalProfile.priority[cardA.type];
    if (priorityDiff !== 0) {
      return priorityDiff;
    }

    return cardA.title.localeCompare(cardB.title);
  });
}

/**
 * Convert TipTap HTML doc content to clean markdown for export,
 * resolving wikilink spans to card titles.
 */
function docHtmlToPlainMarkdown(html: string): string {
  if (!html) return "";
  return html
    // Resolve wikilinks: <span data-wikilink="Title" ...>[[Title]]</span>
    .replace(/<span[^>]*data-wikilink="([^"]*)"[^>]*>.*?<\/span>/g, (_, title) => {
      return `[[${title}]]`;
    })
    .replace(/<h1>(.*?)<\/h1>/g, "# $1\n")
    .replace(/<h2>(.*?)<\/h2>/g, "## $1\n")
    .replace(/<h3>(.*?)<\/h3>/g, "### $1\n")
    .replace(/<blockquote><p>(.*?)<\/p><\/blockquote>/g, "> $1\n")
    .replace(/<pre><code>(.*?)<\/code><\/pre>/gs, "```\n$1\n```\n")
    .replace(/<strong>(.*?)<\/strong>/g, "**$1**")
    .replace(/<em>(.*?)<\/em>/g, "*$1*")
    .replace(/<ul>(.*?)<\/ul>/gs, "$1")
    .replace(/<ol>(.*?)<\/ol>/gs, "$1")
    .replace(/<li>(.*?)<\/li>/g, "- $1\n")
    .replace(/<p><\/p>/g, "\n")
    .replace(/<p>(.*?)<\/p>/g, "$1\n")
    .replace(/<br\s*\/?>/g, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function sortEdgesForGoal(
  edges: Edge[],
  cards: Card[],
  goalProfile: ReturnType<typeof resolveGoalProfile>
): Edge[] {
  return [...edges].sort((a, b) => {
    const sourceA = cards.find((card) => card.id === a.source);
    const sourceB = cards.find((card) => card.id === b.source);
    if (!sourceA || !sourceB) {
      return 0;
    }

    const priorityDiff = goalProfile.priority[sourceB.type] - goalProfile.priority[sourceA.type];
    if (priorityDiff !== 0) {
      return priorityDiff;
    }

    return sourceA.title.localeCompare(sourceB.title);
  });
}
