import type { Card, Edge } from "./types";
import { CARD_TYPE_LABELS } from "./constants";

/**
 * Generate context.md following Claude's optimal reading pattern:
 * 1. Rules first (highest value per word — top of context gets most attention)
 * 2. Structure second (orientation)
 * 3. Workflows third (sequences)
 * 4. Data/References last (supplementary)
 *
 * Brainstorm cards are always excluded.
 * Reference edges are resolved at their specified scope.
 */
export function generateContextMd(
  projectName: string,
  cards: Card[],
  edges: Edge[]
): string {
  const activeCards = cards.filter((c) => c.type !== "brainstorm");
  const hierarchyEdges = edges.filter((e) => e.edgeType === "hierarchy");
  const flowEdges = edges.filter((e) => e.edgeType === "flow");
  const refEdges = edges.filter((e) => e.edgeType === "reference");

  const lines: string[] = [];

  lines.push(`# ${projectName}`);
  lines.push("");
  lines.push(`> Generated by flo from ${activeCards.length} cards and ${edges.length} connections.`);
  lines.push("");

  // --- Section 1: Rules ---
  const ruleCards = activeCards.filter(
    (c) => (c.type === "project" || c.type === "process") && c.body.trim()
  );
  if (ruleCards.length > 0) {
    lines.push("## Rules");
    lines.push("");
    for (const card of ruleCards) {
      const bodyLines = card.body.split("\n").filter((l) => l.trim());
      for (const line of bodyLines) {
        lines.push(`- ${line.trim()}`);
      }
    }
    lines.push("");
  }

  // --- Section 2: Structure ---
  const roots = activeCards.filter(
    (c) => !hierarchyEdges.some((e) => e.target === c.id)
  );
  const childrenOf = (parentId: string): Card[] =>
    hierarchyEdges
      .filter((e) => e.source === parentId)
      .map((e) => activeCards.find((c) => c.id === e.target))
      .filter(Boolean) as Card[];

  if (hierarchyEdges.length > 0) {
    lines.push("## Structure");
    lines.push("");
    function renderTree(card: Card, indent: number) {
      const prefix = "  ".repeat(indent) + "- ";
      const tag = `[${CARD_TYPE_LABELS[card.type]}]`;
      const tags = Array.isArray(card.tags)
        ? card.tags.filter((value): value is string => typeof value === "string")
        : [];
      const tagStr = tags.length ? ` [${tags.map((value) => `#${value}`).join(", ")}]` : "";
      lines.push(`${prefix}${tag} ${card.title}${card.body ? ": " + card.body.split("\n")[0] : ""}${tagStr}`);
      for (const child of childrenOf(card.id)) {
        renderTree(child, indent + 1);
      }
    }
    for (const root of roots) {
      renderTree(root, 0);
    }
    lines.push("");
  }

  // --- Section 3: Workflows ---
  if (flowEdges.length > 0) {
    lines.push("## Workflows");
    lines.push("");

    const flowTargets = new Set(flowEdges.map((e) => e.target));
    const flowStarts = flowEdges
      .filter((e) => !flowTargets.has(e.source))
      .map((e) => e.source);
    const uniqueStarts = [...new Set(flowStarts)];

    for (const startId of uniqueStarts) {
      let current: string | undefined = startId;
      let step = 1;
      const visited = new Set<string>();
      while (current && !visited.has(current)) {
        visited.add(current);
        const card = activeCards.find((c) => c.id === current);
        if (card) {
          lines.push(`${step}. **${card.title}**${card.body ? " — " + card.body.split("\n")[0] : ""}`);
          step++;
        }
        const next = flowEdges.find((e) => e.source === current);
        current = next?.target;
      }
      lines.push("");
    }
  }

  // --- Section 4: Context References ---
  if (refEdges.length > 0) {
    lines.push("## Context References");
    lines.push("");

    for (const ref of refEdges) {
      const source = activeCards.find((c) => c.id === ref.source);
      const target = activeCards.find((c) => c.id === ref.target);
      if (!source || !target) continue;

      switch (ref.referenceScope) {
        case "title":
          lines.push(`- When working on ${source.title}, see also: ${target.title}`);
          break;
        case "summary":
          lines.push(`- When working on ${source.title}, see: **${target.title}** — ${target.body || "(no description)"}`);
          break;
        case "section":
          lines.push(`- When working on ${source.title}, see: **${target.title}** > ${ref.referenceSectionHint || "relevant section"}`);
          break;
        case "full":
        default:
          lines.push(`- When working on ${source.title}, see: **${target.title}** (full context)`);
          if (target.body) lines.push(`  ${target.body}`);
          break;
      }
    }
    lines.push("");
  }

  // --- Section 5: Card Documents ---
  const fullDocCards = activeCards.filter(
    (c) => c.hasDoc && c.docContent.trim()
  );
  const fullRefTargets = new Set(
    refEdges.filter((e) => e.referenceScope === "full").map((e) => e.target)
  );
  const docsToInclude = fullDocCards.filter(
    (c) =>
      !hierarchyEdges.some((e) => e.target === c.id) ||
      fullRefTargets.has(c.id)
  );

  if (docsToInclude.length > 0) {
    lines.push("## Detailed Documents");
    lines.push("");
    for (const card of docsToInclude) {
      lines.push(`### ${card.title}`);
      lines.push("");
      const plainText = card.docContent
        .replace(/<strong>(.*?)<\/strong>/g, "**$1**")
        .replace(/<em>(.*?)<\/em>/g, "*$1*")
        .replace(/<p><\/p>/g, "\n")
        .replace(/<p>(.*?)<\/p>/g, "$1\n")
        .replace(/<li>(.*?)<\/li>/g, "- $1\n")
        .replace(/<[^>]+>/g, "")
        .trim();
      lines.push(plainText);
      lines.push("");
    }
  }

  return lines.join("\n");
}
