import type { WorkspaceTemplate } from "./index";

export const bugTriageTemplate: WorkspaceTemplate = {
  id: "bug-triage",
  name: "Bug Triage / Investigation",
  description: "Track symptoms, isolate the regression path, and keep evidence linked while you move toward a root cause.",
  category: "Investigation",
  goal: "Turn a fuzzy bug report into a reproducible investigation with evidence, hypotheses, and a likely fix path.",
  viewport: { x: 0, y: 20, zoom: 0.8 },
  cards: [
    {
      id: "bug-incident",
      type: "project",
      title: "Checkout fails for returning users",
      body: "Intermittent 500s appear after payment method selection, mostly on repeat purchases.",
      position: { x: 420, y: 100 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Reported behavior</h2><p>The UI recovers poorly after failure and sometimes double-submits the order request on refresh.</p>",
    },
    {
      id: "bug-symptoms",
      type: "process",
      title: "Capture reproduction path",
      body: "Define browser, account state, and timing needed to trigger the failure reliably.",
      position: { x: 120, y: 300 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
    {
      id: "bug-logs",
      type: "process",
      title: "Inspect logs and traces",
      body: "Correlate checkout API traces with payment provider responses and cache invalidation timing.",
      position: { x: 420, y: 300 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Evidence to gather</h2><ul><li>Request IDs from failed checkouts</li><li>Upstream payment gateway codes</li><li>Cache hit ratio during failures</li></ul>",
    },
    {
      id: "bug-isolate",
      type: "process",
      title: "Isolate likely regression",
      body: "Compare the new saved-card path against the previous guest checkout implementation.",
      position: { x: 720, y: 300 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
      agentHint: "Bias toward the narrowest code path unique to returning users before expanding the search.",
    },
    {
      id: "bug-sentry",
      type: "reference",
      title: "Sentry issue and support tickets",
      body: "Primary incident evidence from customer reports and stack traces.",
      position: { x: 120, y: 520 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Notes</h2><p>Most failures reference a missing cart token after the payment intent is refreshed. Ticket volume spiked after release 2026.03.28.</p>",
    },
    {
      id: "bug-hypotheses",
      type: "brainstorm",
      title: "Root cause hypotheses",
      body: "Saved payment token invalidation, stale cart cache, or duplicate submit race on redirect recovery.",
      position: { x: 720, y: 520 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
  ],
  edges: [
    { id: "bug-h1", source: "bug-incident", target: "bug-symptoms", edgeType: "hierarchy" },
    { id: "bug-h2", source: "bug-incident", target: "bug-logs", edgeType: "hierarchy" },
    { id: "bug-f1", source: "bug-symptoms", target: "bug-logs", edgeType: "flow" },
    { id: "bug-f2", source: "bug-logs", target: "bug-isolate", edgeType: "flow" },
    { id: "bug-f3", source: "bug-isolate", target: "bug-hypotheses", edgeType: "flow" },
    {
      id: "bug-r1",
      source: "bug-logs",
      target: "bug-sentry",
      edgeType: "reference",
      referenceScope: "summary",
    },
  ],
};
