import type { WorkspaceTemplate } from "./index";

export const productDiscoveryTemplate: WorkspaceTemplate = {
  id: "product-discovery",
  name: "Product Discovery / Research",
  description: "Frame the problem, capture user evidence, and connect opportunities to the next experiments you want an agent to expand.",
  category: "Discovery",
  goal: "Organize research evidence into a crisp problem statement, target segment, and experiment backlog.",
  viewport: { x: 10, y: 0, zoom: 0.77 },
  cards: [
    {
      id: "disc-goal",
      type: "project",
      title: "Reduce churn in team reporting",
      body: "Clarify why admins stop using weekly reports and where the product can create repeat value.",
      position: { x: 420, y: 100 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Objective</h2><p>Identify the most painful reporting jobs-to-be-done for operations managers and define a credible v1 improvement path.</p>",
    },
    {
      id: "disc-segment",
      type: "process",
      title: "Define target segment",
      body: "Focus on operations leads at 50-250 person companies with recurring executive reporting needs.",
      position: { x: 120, y: 300 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
    {
      id: "disc-jtbd",
      type: "process",
      title: "Map jobs and friction",
      body: "Capture the recurring decisions, data pulls, and manual spreadsheet work behind each report.",
      position: { x: 420, y: 300 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Interview prompts</h2><ul><li>What triggers report creation?</li><li>Which numbers require the most cleanup?</li><li>Who reviews the final output?</li></ul>",
    },
    {
      id: "disc-experiments",
      type: "process",
      title: "Prioritize experiments",
      body: "Sort solution bets by confidence, implementation cost, and expected retention impact.",
      position: { x: 720, y: 300 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
      agentHint: "Keep experiments concrete enough to test within one sprint. Avoid broad redesign concepts until a single pain point wins.",
    },
    {
      id: "disc-interviews",
      type: "reference",
      title: "Interview notes",
      body: "Condensed quotes, patterns, and request frequency across recent customer calls.",
      position: { x: 120, y: 520 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Patterns</h2><p>Users export raw CSVs because the current weekly report is hard to tailor for leadership. They want fewer manual pivots, not more charts.</p>",
    },
    {
      id: "disc-opps",
      type: "brainstorm",
      title: "Opportunity spaces",
      body: "Template library, report scheduling defaults, and confidence scoring for incomplete source data.",
      position: { x: 720, y: 520 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
  ],
  edges: [
    { id: "disc-h1", source: "disc-goal", target: "disc-segment", edgeType: "hierarchy" },
    { id: "disc-h2", source: "disc-goal", target: "disc-jtbd", edgeType: "hierarchy" },
    { id: "disc-f1", source: "disc-segment", target: "disc-jtbd", edgeType: "flow" },
    { id: "disc-f2", source: "disc-jtbd", target: "disc-experiments", edgeType: "flow" },
    { id: "disc-f3", source: "disc-experiments", target: "disc-opps", edgeType: "flow" },
    {
      id: "disc-r1",
      source: "disc-jtbd",
      target: "disc-interviews",
      edgeType: "reference",
      referenceScope: "summary",
    },
  ],
};
