import type { WorkspaceTemplate } from "./index";

export const sampleWorkspaceTemplate: WorkspaceTemplate = {
  id: "sample-nextjs-auth",
  name: "Sample Workspace",
  description: "A complete example showing how flo can map a real implementation plan, supporting references, and agent-ready execution hints.",
  category: "Sample",
  goal: "Implement OAuth sign-in for a Next.js customer portal with secure session handling and a staged production rollout.",
  viewport: { x: 0, y: 0, zoom: 0.72 },
  cards: [
    {
      id: "sample-goal",
      type: "project",
      title: "Add OAuth to the customer portal",
      body: "Ship Google and GitHub sign-in for the Next.js app, keep sessions durable, and make rollout safe for existing accounts.",
      position: { x: 360, y: 80 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Outcome</h2><p>Users can authenticate with Google or GitHub, existing email/password accounts can link providers, and support has a clear rollback path.</p><h3>Success checks</h3><ul><li>Sign-in works in local, staging, and production.</li><li>Session cookies rotate safely.</li><li>Account linking does not create duplicate users.</li></ul>",
    },
    {
      id: "sample-strategy",
      type: "process",
      title: "Choose auth strategy and adapter",
      body: "Settle on NextAuth, define provider scopes, and pick the user/session storage model before UI work begins.",
      position: { x: 80, y: 290 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Decision points</h2><ul><li>Use database sessions instead of JWT-only storage.</li><li>Normalize provider profile fields before persistence.</li><li>Reserve a linking path for existing password users.</li></ul>",
      agentHint: "Start with the auth adapter and schema decisions first. UI work becomes simpler once callback behavior and session shape are fixed.",
    },
    {
      id: "sample-schema",
      type: "process",
      title: "Update schema and account linking",
      body: "Add provider account tables, migration steps, and logic for linking OAuth identities to existing users.",
      position: { x: 340, y: 290 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Migration plan</h2><ol><li>Create account and session tables.</li><li>Backfill nullable provider columns.</li><li>Prevent duplicate users on matching email addresses.</li></ol>",
    },
    {
      id: "sample-ui",
      type: "process",
      title: "Build sign-in and settings flows",
      body: "Add provider buttons, loading/error states, and an account settings view for linking or unlinking providers.",
      position: { x: 620, y: 290 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
    {
      id: "sample-rollout",
      type: "process",
      title: "Stage rollout and monitor auth health",
      body: "Enable internally first, then expand to a pilot segment while tracking callback failures and duplicate accounts.",
      position: { x: 880, y: 290 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Rollout checkpoints</h2><ul><li>Verify provider credentials per environment.</li><li>Track failed callback rate and account-link conflicts.</li><li>Prepare a temporary provider disable switch.</li></ul>",
      agentHint: "Keep telemetry and rollback tasks in scope. Auth launches fail when monitoring is treated as cleanup instead of core work.",
    },
    {
      id: "sample-nextauth-docs",
      type: "reference",
      title: "NextAuth provider and callback docs",
      body: "Reference for providers, callbacks, adapter setup, and session configuration in the App Router.",
      position: { x: 80, y: 540 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Relevant sections</h2><p>Provider configuration, signIn/session callbacks, Prisma adapter setup, and securing server actions that rely on session state.</p>",
    },
    {
      id: "sample-security",
      type: "reference",
      title: "Security and account migration checklist",
      body: "Capture PKCE requirements, cookie settings, domain constraints, and support-ready migration notes.",
      position: { x: 620, y: 540 },
      collapsed: false,
      hasDoc: true,
      docContent:
        "<h2>Checklist</h2><ul><li>Verify callback URLs in each environment.</li><li>Use secure, httpOnly cookies in production.</li><li>Document how to recover users with mismatched provider emails.</li></ul>",
    },
    {
      id: "sample-open-questions",
      type: "brainstorm",
      title: "Unknowns to resolve before release",
      body: "Enterprise SSO timing, provider-specific scopes, and whether unlinking should require password fallback first.",
      position: { x: 940, y: 540 },
      collapsed: false,
      hasDoc: false,
      docContent: "",
    },
  ],
  edges: [
    { id: "sample-h1", source: "sample-goal", target: "sample-strategy", edgeType: "hierarchy" },
    { id: "sample-h2", source: "sample-goal", target: "sample-schema", edgeType: "hierarchy" },
    { id: "sample-f1", source: "sample-strategy", target: "sample-schema", edgeType: "flow" },
    { id: "sample-f2", source: "sample-schema", target: "sample-ui", edgeType: "flow" },
    { id: "sample-f3", source: "sample-ui", target: "sample-rollout", edgeType: "flow" },
    {
      id: "sample-r1",
      source: "sample-strategy",
      target: "sample-nextauth-docs",
      edgeType: "reference",
      referenceScope: "full",
    },
    {
      id: "sample-r2",
      source: "sample-schema",
      target: "sample-security",
      edgeType: "reference",
      referenceScope: "section",
      referenceSectionHint: "Checklist",
    },
    {
      id: "sample-r3",
      source: "sample-rollout",
      target: "sample-open-questions",
      edgeType: "reference",
      referenceScope: "title",
    },
  ],
};
